package com.hani.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;

public class AboutUs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.id
     * 创建时间 : 2017-01-31 14:51:08
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.type
     * 创建时间 : 2017-01-31 14:51:08
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.title
     * 创建时间 : 2017-01-31 14:51:08
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.remark
     * 创建时间 : 2017-01-31 14:51:08
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.content
     * 创建时间 : 2017-01-31 14:51:08
     */
    private String content;

    /**
     * about_us表的操作属性:serialVersionUID
     * 创建时间 : 2017-01-31 14:51:08
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 about_us.id的get方法 
     * 创建时间 : 2017-01-31 14:51:08
     */
    public Integer getId() {
        return id;
    }

    /**
     * 数据字段 about_us.id的set方法
     * 创建时间 : 2017-01-31 14:51:08
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 数据字段 about_us.type的get方法 
     * 创建时间 : 2017-01-31 14:51:08
     */
    public Boolean getType() {
        return type;
    }

    /**
     * 数据字段 about_us.type的set方法
     * 创建时间 : 2017-01-31 14:51:08
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * 数据字段 about_us.title的get方法 
     * 创建时间 : 2017-01-31 14:51:08
     */
    public String getTitle() {
        return title;
    }

    /**
     * 数据字段 about_us.title的set方法
     * 创建时间 : 2017-01-31 14:51:08
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 数据字段 about_us.remark的get方法 
     * 创建时间 : 2017-01-31 14:51:08
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 数据字段 about_us.remark的set方法
     * 创建时间 : 2017-01-31 14:51:08
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 数据字段 about_us.content的get方法 
     * 创建时间 : 2017-01-31 14:51:08
     */
    public String getContent() {
        return content;
    }

    /**
     * 数据字段 about_us.content的set方法
     * 创建时间 : 2017-01-31 14:51:08
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}