package com.hani.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     * 创建时间 : 2016-12-12 23:05:47
     */
    private Integer id;

    /**
     * 用户名 -- admin.user_name
     * 创建时间 : 2016-12-12 23:05:47
     */
    private String userName;

    /**
     * 密码 -- admin.pwd
     * 创建时间 : 2016-12-12 23:05:47
     */
    private String pwd;

    /**
     * 创建时间 -- admin.create_time
     * 创建时间 : 2016-12-12 23:05:47
     */
    private Date createTime;

    /**
     * 修改时间 -- admin.modify_time
     * 创建时间 : 2016-12-12 23:05:47
     */
    private Date modifyTime;

    /**
     * admin表的操作属性:serialVersionUID
     * 创建时间 : 2016-12-12 23:05:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 admin.id的get方法 
     * 创建时间 : 2016-12-12 23:05:47
     */
    public Integer getId() {
        return id;
    }

    /**
     * 数据字段 admin.id的set方法
     * 创建时间 : 2016-12-12 23:05:47
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 数据字段 admin.user_name的get方法 
     * 创建时间 : 2016-12-12 23:05:47
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 数据字段 admin.user_name的set方法
     * 创建时间 : 2016-12-12 23:05:47
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 数据字段 admin.pwd的get方法 
     * 创建时间 : 2016-12-12 23:05:47
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * 数据字段 admin.pwd的set方法
     * 创建时间 : 2016-12-12 23:05:47
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * 数据字段 admin.create_time的get方法 
     * 创建时间 : 2016-12-12 23:05:47
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 admin.create_time的set方法
     * 创建时间 : 2016-12-12 23:05:47
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 admin.modify_time的get方法 
     * 创建时间 : 2016-12-12 23:05:47
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * 数据字段 admin.modify_time的set方法
     * 创建时间 : 2016-12-12 23:05:47
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}