package com.hani.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;

public class BizInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_info.id
     * 创建时间 : 2017-01-31 14:53:08
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_info.type
     * 创建时间 : 2017-01-31 14:53:08
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_info.title
     * 创建时间 : 2017-01-31 14:53:08
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_info.content
     * 创建时间 : 2017-01-31 14:53:08
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_info.pic_url
     * 创建时间 : 2017-01-31 14:53:08
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_info.remark
     * 创建时间 : 2017-01-31 14:53:08
     */
    private String remark;

    /**
     * biz_info表的操作属性:serialVersionUID
     * 创建时间 : 2017-01-31 14:53:08
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 biz_info.id的get方法 
     * 创建时间 : 2017-01-31 14:53:08
     */
    public Integer getId() {
        return id;
    }

    /**
     * 数据字段 biz_info.id的set方法
     * 创建时间 : 2017-01-31 14:53:08
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 数据字段 biz_info.type的get方法 
     * 创建时间 : 2017-01-31 14:53:08
     */
    public Boolean getType() {
        return type;
    }

    /**
     * 数据字段 biz_info.type的set方法
     * 创建时间 : 2017-01-31 14:53:08
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * 数据字段 biz_info.title的get方法 
     * 创建时间 : 2017-01-31 14:53:08
     */
    public String getTitle() {
        return title;
    }

    /**
     * 数据字段 biz_info.title的set方法
     * 创建时间 : 2017-01-31 14:53:08
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 数据字段 biz_info.content的get方法 
     * 创建时间 : 2017-01-31 14:53:08
     */
    public String getContent() {
        return content;
    }

    /**
     * 数据字段 biz_info.content的set方法
     * 创建时间 : 2017-01-31 14:53:08
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * 数据字段 biz_info.pic_url的get方法 
     * 创建时间 : 2017-01-31 14:53:08
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * 数据字段 biz_info.pic_url的set方法
     * 创建时间 : 2017-01-31 14:53:08
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * 数据字段 biz_info.remark的get方法 
     * 创建时间 : 2017-01-31 14:53:08
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 数据字段 biz_info.remark的set方法
     * 创建时间 : 2017-01-31 14:53:08
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}